services:
  postgres:
    container_name: pg_${RUN_MODE}
    image: postgres
    restart: always
    environment:
      TZ: ${TZ}
      PGTZ: ${TZ}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: api_${RUN_MODE}
    depends_on:
      - postgres
    build:
      context: ..
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
      - 9001:9001
    restart: on-failure

  admin_api:
    container_name: admin_api_${RUN_MODE}
    depends_on:
      - postgres
    build:
      context: ..
      dockerfile: ./apps/admin-api/Dockerfile
    env_file:
      - .env
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    restart: on-failure

volumes:
  db:
